# Generated by Django 5.1 on 2024-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detallesPedidos', '0001_initial'),
        ('productos', '0002_alter_productos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('espera', 'espera'), ('preparacion', 'preparacion'), ('terminado', 'terminado')], default='espera', max_length=30)),
                ('productos', models.ManyToManyField(through='detallesPedidos.DetallePedido', to='productos.productos')),
            ],
        ),
    ]
