# Generated by Django 5.1 on 2024-10-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detallesPedidos', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0002_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedidos'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos'),
        ),
    ]
