# Generated by Django 5.1 on 2024-10-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallesPedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(choices=[('llevar', 'llevar'), ('consumir', 'para consumo en el sitio')], default='consumir', max_length=30),
        ),
    ]
